/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financely;

/**
 *
 * @author asus
 */
public class Incomes extends javax.swing.JFrame {

    /**
     * Creates new form Incomes
     */
    public Incomes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoriesIncomes = new javax.swing.JComboBox<>();
        TableIncomes = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonEditIncomes = new javax.swing.JButton();
        NotesIncomes = new javax.swing.JTextField();
        AmountIncomes = new javax.swing.JTextField();
        ButtonAddIncomes = new javax.swing.JButton();
        ButtonClearIncomes = new javax.swing.JButton();
        ButtonDeleteIncomes = new javax.swing.JButton();
        UIManageIncomes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financely");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategoriesIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        CategoriesIncomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Item 2", "Item 3", "Item 4" }));
        CategoriesIncomes.setToolTipText("");
        CategoriesIncomes.setBorder(null);
        getContentPane().add(CategoriesIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 285, 290, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableIncomes.setViewportView(jTable1);

        getContentPane().add(TableIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 340, 200));

        ButtonEditIncomes.setBackground(new java.awt.Color(19, 196, 250));
        ButtonEditIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonEditIncomes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEditIncomes.setText("Save Edit");
        ButtonEditIncomes.setBorder(null);
        ButtonEditIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEditIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 120, 47));

        NotesIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        NotesIncomes.setBorder(null);
        NotesIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(NotesIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 474, 270, 35));

        AmountIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        AmountIncomes.setBorder(null);
        AmountIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(AmountIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 381, 270, 35));

        ButtonAddIncomes.setBackground(new java.awt.Color(19, 196, 250));
        ButtonAddIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonAddIncomes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAddIncomes.setText("Add");
        ButtonAddIncomes.setBorder(null);
        ButtonAddIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAddIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 380, 47));

        ButtonClearIncomes.setBackground(new java.awt.Color(19, 196, 250));
        ButtonClearIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonClearIncomes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClearIncomes.setText("Delete");
        ButtonClearIncomes.setBorder(null);
        ButtonClearIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonClearIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 120, 47));

        ButtonDeleteIncomes.setBackground(new java.awt.Color(19, 196, 250));
        ButtonDeleteIncomes.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonDeleteIncomes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDeleteIncomes.setText("Clear");
        ButtonDeleteIncomes.setBorder(null);
        ButtonDeleteIncomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteIncomesActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDeleteIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 120, 47));

        UIManageIncomes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Manage Incomes - 2.png"))); // NOI18N
        getContentPane().add(UIManageIncomes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmountIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountIncomesActionPerformed

    private void NotesIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotesIncomesActionPerformed

    private void ButtonEditIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditIncomesActionPerformed

    private void ButtonAddIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAddIncomesActionPerformed

    private void ButtonClearIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonClearIncomesActionPerformed

    private void ButtonDeleteIncomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteIncomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteIncomesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incomes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incomes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountIncomes;
    private javax.swing.JButton ButtonAddIncomes;
    private javax.swing.JButton ButtonClearIncomes;
    private javax.swing.JButton ButtonDeleteIncomes;
    private javax.swing.JButton ButtonEditIncomes;
    private javax.swing.JComboBox<String> CategoriesIncomes;
    private javax.swing.JTextField NotesIncomes;
    private javax.swing.JScrollPane TableIncomes;
    private javax.swing.JLabel UIManageIncomes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
