package financely;

import javax.swing.BorderFactory;

/**
 *
 * @author Kelompok 3 RPL 4A
 * - Afwa Afini
 * - Azka Ahmad Azharan
 * - Hanisah Fildza Annafisah
 * - Innaka Dylee
 */
public class Landing extends javax.swing.JFrame {

    public Landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonLoginLanding = new javax.swing.JButton();
        ButtonRegisterLanding = new javax.swing.JButton();
        UILanding = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonLoginLanding.setBackground(new java.awt.Color(19, 196, 250));
        ButtonLoginLanding.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        ButtonLoginLanding.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLoginLanding.setText("Login");
        ButtonLoginLanding.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
        ButtonLoginLanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginLandingActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLoginLanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 290, 47));

        ButtonRegisterLanding.setBackground(new java.awt.Color(19, 196, 250));
        ButtonRegisterLanding.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        ButtonRegisterLanding.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegisterLanding.setText("Register Now");
        ButtonRegisterLanding.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
        ButtonRegisterLanding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterLandingActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegisterLanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 290, 47));

        UILanding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Landing.png"))); // NOI18N
        getContentPane().add(UILanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegisterLandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterLandingActionPerformed
        Register RegisterPage = new Register();
        RegisterPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegisterLandingActionPerformed

    private void ButtonLoginLandingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginLandingActionPerformed
        Login LoginPage = new Login();
        LoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonLoginLandingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLoginLanding;
    private javax.swing.JButton ButtonRegisterLanding;
    private javax.swing.JLabel UILanding;
    // End of variables declaration//GEN-END:variables
}
