/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financely;

/**
 *
 * @author azkaa
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLogin = new javax.swing.JTextField();
        PasswordLogin = new javax.swing.JPasswordField();
        ButtonLogin = new javax.swing.JButton();
        QuestionRegister = new javax.swing.JLabel();
        RegistLink = new javax.swing.JLabel();
        UILogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financely");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        UsernameLogin.setBorder(null);
        UsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameLoginActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 207, 270, 35));

        PasswordLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PasswordLogin.setBorder(null);
        PasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordLoginActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 302, 270, 35));

        ButtonLogin.setBackground(new java.awt.Color(19, 196, 250));
        ButtonLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogin.setText("Get Started");
        ButtonLogin.setBorder(null);
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 380, 290, 47));

        QuestionRegister.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        QuestionRegister.setForeground(new java.awt.Color(255, 255, 255));
        QuestionRegister.setText("Don't have an account ? ");
        getContentPane().add(QuestionRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        RegistLink.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        RegistLink.setForeground(new java.awt.Color(19, 196, 250));
        RegistLink.setText("Register");
        getContentPane().add(RegistLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        UILogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Login.png"))); // NOI18N
        getContentPane().add(UILogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameLoginActionPerformed

    private void PasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordLoginActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JLabel QuestionRegister;
    private javax.swing.JLabel RegistLink;
    private javax.swing.JLabel UILogin;
    private javax.swing.JTextField UsernameLogin;
    // End of variables declaration//GEN-END:variables
}
