package financely;

import com.mysql.jdbc.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 3 RPL 4A
 * - Afwa Afini
 * - Azka Ahmad Azharan
 * - Hanisah Fildza Annafisah
 * - Innaka Dylee
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLogin = new javax.swing.JTextField();
        PasswordLogin = new javax.swing.JPasswordField();
        ButtonLogin = new javax.swing.JButton();
        QuestionRegister = new javax.swing.JLabel();
        RegistLink = new javax.swing.JLabel();
        UILogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financely");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        UsernameLogin.setBorder(null);
        getContentPane().add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 207, 270, 35));

        PasswordLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PasswordLogin.setBorder(null);
        getContentPane().add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 302, 270, 35));

        ButtonLogin.setBackground(new java.awt.Color(19, 196, 250));
        ButtonLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogin.setText("Get Started");
        ButtonLogin.setBorder(null);
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 380, 290, 47));

        QuestionRegister.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        QuestionRegister.setForeground(new java.awt.Color(255, 255, 255));
        QuestionRegister.setText("Don't have an account ? ");
        getContentPane().add(QuestionRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        RegistLink.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        RegistLink.setForeground(new java.awt.Color(19, 196, 250));
        RegistLink.setText("Register");
        RegistLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistLinkMouseClicked(evt);
            }
        });
        getContentPane().add(RegistLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        UILogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Login.png"))); // NOI18N
        getContentPane().add(UILogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        String username = UsernameLogin.getText();
        String password = PasswordLogin.getText();
        
        if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Username not filled");
        } else if (password.equals("")){
            JOptionPane.showMessageDialog(null, "Password not filled");
        } else {
            try {
                java.sql.Connection Vconn = (Connection)DBconnect.configDB();
                
                String loginQuery = "SELECT * FROM datauser WHERE username = ? AND password = ?";
                java.sql.PreparedStatement loginStatement = Vconn.prepareStatement(loginQuery);
                loginStatement.setString(1, username);
                loginStatement.setString(2, password);
                
                java.sql.ResultSet loginResult = loginStatement.executeQuery();
                
                if(loginResult.next()) {
                    int userID = loginResult.getInt("ID");
                    
                    Dashboard DashboardPage = new Dashboard(userID);
                    DashboardPage.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Username or password are wrong");               
                }
                
                cleanForm();
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Login Failed", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void RegistLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistLinkMouseClicked
        Register RegisterPage = new Register();
        RegisterPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistLinkMouseClicked

    private void cleanForm(){
        UsernameLogin.setText("");        
        PasswordLogin.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JLabel QuestionRegister;
    private javax.swing.JLabel RegistLink;
    private javax.swing.JLabel UILogin;
    private javax.swing.JTextField UsernameLogin;
    // End of variables declaration//GEN-END:variables
}
