/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financely;

/**
 *
 * @author azkaa
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LoginLink = new javax.swing.JLabel();
        EmailRegister = new javax.swing.JTextField();
        UsernameRegister = new javax.swing.JTextField();
        PasswordRegister = new javax.swing.JPasswordField();
        ButtonRegister = new javax.swing.JButton();
        QuestionLogin = new javax.swing.JLabel();
        UIRegister = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financely");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLink.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        LoginLink.setForeground(new java.awt.Color(19, 196, 250));
        LoginLink.setText("Login");
        getContentPane().add(LoginLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 530, -1, -1));

        EmailRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        EmailRegister.setBorder(null);
        EmailRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(EmailRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 205, 270, 35));

        UsernameRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        UsernameRegister.setBorder(null);
        UsernameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 299, 270, 35));

        PasswordRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PasswordRegister.setBorder(null);
        PasswordRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 394, 270, 35));

        ButtonRegister.setBackground(new java.awt.Color(19, 196, 250));
        ButtonRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegister.setText("Register");
        ButtonRegister.setBorder(null);
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 290, 47));

        QuestionLogin.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        QuestionLogin.setForeground(new java.awt.Color(255, 255, 255));
        QuestionLogin.setText("Already have an account ? ");
        getContentPane().add(QuestionLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 530, -1, -1));

        UIRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Register.png"))); // NOI18N
        getContentPane().add(UIRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailRegisterActionPerformed

    private void UsernameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameRegisterActionPerformed

    private void PasswordRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordRegisterActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JTextField EmailRegister;
    private javax.swing.JLabel LoginLink;
    private javax.swing.JPasswordField PasswordRegister;
    private javax.swing.JLabel QuestionLogin;
    private javax.swing.JLabel UIRegister;
    private javax.swing.JTextField UsernameRegister;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
