package financely;

import com.mysql.jdbc.Connection;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelompok 3 RPL 4A
 * - Afwa Afini
 * - Azka Ahmad Azharan
 * - Hanisah Fildza Annafisah
 * - Innaka Dylee
 */
public class Register extends javax.swing.JFrame {

    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        LoginLink = new javax.swing.JLabel();
        EmailRegister = new javax.swing.JTextField();
        UsernameRegister = new javax.swing.JTextField();
        PasswordRegister = new javax.swing.JPasswordField();
        ButtonRegister = new javax.swing.JButton();
        QuestionLogin = new javax.swing.JLabel();
        UIRegister = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Financely");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLink.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        LoginLink.setForeground(new java.awt.Color(19, 196, 250));
        LoginLink.setText("Login");
        LoginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLinkMouseClicked(evt);
            }
        });
        getContentPane().add(LoginLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 530, -1, -1));

        EmailRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        EmailRegister.setBorder(null);
        getContentPane().add(EmailRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 205, 270, 35));

        UsernameRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        UsernameRegister.setBorder(null);
        getContentPane().add(UsernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 299, 270, 35));

        PasswordRegister.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        PasswordRegister.setBorder(null);
        getContentPane().add(PasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 394, 270, 35));

        ButtonRegister.setBackground(new java.awt.Color(19, 196, 250));
        ButtonRegister.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        ButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegister.setText("Register");
        ButtonRegister.setBorder(null);
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 290, 47));

        QuestionLogin.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        QuestionLogin.setForeground(new java.awt.Color(255, 255, 255));
        QuestionLogin.setText("Already have an account ? ");
        getContentPane().add(QuestionLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 530, -1, -1));

        UIRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIComponent/Register.png"))); // NOI18N
        getContentPane().add(UIRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        String email = EmailRegister.getText();
        String username = UsernameRegister.getText();
        String password = PasswordRegister.getText();
        
        if (email.equals("")){
            JOptionPane.showMessageDialog(null, "Email not filled");
        } else if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Username not filled");
        } else if (password.equals("")){
            JOptionPane.showMessageDialog(null, "Password not filled");
        } else if (!validateEmail(email)){
            JOptionPane.showMessageDialog(null, "The email must end in @gmail.com");
        } else {
            try {
                java.sql.Connection Vconn = (Connection)DBconnect.configDB();
                
                String emailCheckQuery = "SELECT * FROM datauser WHERE email = ?";
                java.sql.PreparedStatement emailCheckStatement = Vconn.prepareStatement(emailCheckQuery);
                emailCheckStatement.setString(1, email);
                
                java.sql.ResultSet emailCheckResult = emailCheckStatement.executeQuery();
                
                if (emailCheckResult.next()){
                    JOptionPane.showMessageDialog(null, "Email already registered, please use another email.", "Create Account Failed", JOptionPane.OK_OPTION);
                } else {
                    String usernameCheckQuery = "SELECT * FROM datauser WHERE username = ?";
                    java.sql.PreparedStatement usernameCheckStatement = Vconn.prepareStatement(usernameCheckQuery);
                    usernameCheckStatement.setString(1, username);

                    java.sql.ResultSet usernameCheckResult = usernameCheckStatement.executeQuery();

                    if (usernameCheckResult.next()){
                        JOptionPane.showMessageDialog(null, "Username already registered, please choose another username.", "Create Account Failed", JOptionPane.OK_OPTION);
                    } else {
                        String registrationQuery = "INSERT INTO datauser (email, username, password) VALUES (?, ?, ?)";                   
                        java.sql.PreparedStatement registrationStatement = Vconn.prepareStatement(registrationQuery);
                        registrationStatement.setString(1, email);
                        registrationStatement.setString(2, username);
                        registrationStatement.setString(3, password);
                        registrationStatement.execute();

                        Login LoginPage = new Login();
                        LoginPage.setVisible(true);
                        this.setVisible(false);

                        JOptionPane.showMessageDialog(null, "Please log in to continue.", "Create Account Successfully", JOptionPane.PLAIN_MESSAGE);
                    }
                }                            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Create Account Failed", JOptionPane.OK_OPTION);
            }
            cleanForm();            
        }
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void LoginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLinkMouseClicked
        Login LoginPage = new Login();
        LoginPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoginLinkMouseClicked

    public static boolean validateEmail(String email){
        String regex = "^\\S+@gmail.com$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        
        return matcher.matches();
    }
    
    private void cleanForm(){
        EmailRegister.setText("");
        UsernameRegister.setText("");
        PasswordRegister.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JTextField EmailRegister;
    private javax.swing.JLabel LoginLink;
    private javax.swing.JPasswordField PasswordRegister;
    private javax.swing.JLabel QuestionLogin;
    private javax.swing.JLabel UIRegister;
    private javax.swing.JTextField UsernameRegister;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
